### ISSUE TITLE
Crashes the game.

### ISSUE THREAD

**Issue by sinkingsage** [ItsEasyActually/SA1_Chars#1]
My lantern engine is updated along with the new .dll, whether I enable it or disable it, when I use the character pack, the game crashes as soon as it tries to render a 3D model.

Update: Disabled every single other mod and the game still crashes.

**Comment by ItsEasyActually** [comment]
You need to update your d3d8.dll file. You can get it here: https://github.com/crosire/d3d8to9/releases 

It goes in the root of your SADX install.

If the mod is still crashing after this, force an update to ensure it downloaded correctly. Also ensure you're loading the Dreamcast Character Pack last.

**Comment by sinkingsage** [comment]
Already have, did it again to make sure. Still crashes.
No other mod but the character pack, still crashes.

Update: The forced update fixed it.
Thank you.
