### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by ItsEasyActually** [ItsEasyActually/SA1_Chars#10]
I'm currently looking for suggestions and an open discussion on some ideas for configuration for the mod. I've already gotten some feedback prior to opening this issue, so I'll include those ideas down below. Feel free to offer up any other suggestions or additions plus let me know if any existing options are something you really want considered.

## Current suggestions
- Silver Sonic from the Mystic Ruins Base as a skin for Metal Sonic.
- DX style hand toggle.
- Toggle for turning on and off DC models per character.

#### If you have other suggestions or requests with the current suggestions I have listed, do share them here or [Tweet me](https://twitter.com/ItsEasyActually).

**Comment by PiKeyAr** [comment]
How about enable or disable "holding" animations from the Japanese version. Those look hilarious.

**Comment by slx7R4GDZM** [comment]
Would it be possible to rig the low poly Sonic model from Sky Chase Act 1 as a Sonic skin?

**Comment by ItsEasyActually** [comment]
@PiKeyAr That sounds like it could be fun. I want to get the animations from the Japanese version at some point since there's minor differences.

@slx7R4GDZM This game doesn't use rigging, and that model has less parts than Sonic's normal model. It would be possible to create something that would work and look good, but that's beyond the scope of this project.

**Comment by SurDno** [comment]
@slx7R4GDZM, since DC Sky Chase uses early Sonic Saturn models, you may want to check this: youtu.be/me-YMJblWUE

**Comment by SurDno** [comment]
Well, I pretty much love DX dark "modern" style, while DC textures look more like Sonic Mania light-blue style, though port screws face animations. Maybe some kind of GC-like textures for DC models? That would be nice.

**Comment by DisapprovingOwl** [comment]
Quick question re: the proposed "DX-style hands" option. While I love the fact the DX hands have actual modelled fingers, the DX team managed to screw up Amy/Tikal's hands so that they have really long and oddly-angled fingers. Bizarrely enough, Tails - who has similarly small hands in the DC version - seems to have proportionally correct hands in DX. 

My question is - would it be possible to use Tails' hands as a base for the "DX-style" Amy/Tikal hands instead of their actual DX hands, so that they remain proportionally correct compared to the DC version?

**Comment by ItsEasyActually** [comment]
I would need to adjust the hands in general. None of the DX hands really look good with the DC models. Honestly, just modeling fingers for them in a style like the DC models would probably be the best option for that very reason.

**Comment by SurDno** [comment]
He did not ask to adjust DX-hands to DC models. He asked to adjust Tails' DX-hands (that look like DC) to DX Amy and DX Tikal.

**Comment by ItsEasyActually** [comment]
I said I would need to adjust them in general because they look out of place, size wise and design wise. Please read what I post next time. The reason I said making DC styled hands would be better is because the DX hands look out of place in general. Tails, Amy's, Sonic's, doesn't matter, they look out of place with the DC models but the puppet hands are silly looking as well.

**Comment by DisapprovingOwl** [comment]
@ItsEasyActually - Ah, custom hands that'd fit better with the DC style models sounds like an even better solution, yes. Slightly squarer fingers (i.e. more like the SA2 DC models in terms of the shape of the individual fingers, but keeping everything in proportion with the original SA DC models' hands) would probably be the best option, as then it'd look more like something that could have been achievable on the Dreamcast. = )

I'm usually all for as much authenticity to the Dreamcast version as possible in terms of which mods I use, but I have to admit I'd be interested to use the proposed custom hands feature if it does get added in future.

One last question re: the hands - as well as the character models themselves, if you went ahead with implementing this option would you also be planning on making this change to the "Zero holding Amy" model too for consistency? I think that's the only other model I can think of which would need it, as both sets of Sonic/Tails' Sky Chase models are lower-poly anyway and only seen in close up fairly briefly when they appear.
