### ISSUE TITLE
𝘜𝘝 𝘌𝘺𝘦 𝘚𝘰𝘯𝘪𝘬𝘬𝘶

### ISSUE THREAD

**Issue by KayaneRF** [ItsEasyActually/SA1_Chars#12]
𝘚𝘢𝘭𝘶𝘵, 𝘐 𝘥𝘦𝘵𝘦𝘤𝘵 𝘜𝘝 𝘴𝘪𝘻𝘦 𝘧𝘰𝘳 𝘦𝘺𝘦 𝘥𝘪𝘷𝘦𝘳𝘨𝘦𝘯𝘵. ∧∧ 𝘑𝘦 𝘷𝘰𝘶𝘴 𝘳𝘦𝘮𝘦𝘳𝘤𝘪𝘦
![sonikkusa89136](https://user-images.githubusercontent.com/34458147/33853221-3dd25cfe-de8b-11e7-8ab9-44da7d295187.png)
![sonikkudx87204](https://user-images.githubusercontent.com/34458147/33853220-3bd79d56-de8b-11e7-9663-525dade7c625.png)
–𝘒𝘢𝘺𝘢𝘯𝘦

**Comment by ItsEasyActually** [comment]
It looks like a precision issue which could be for any number of reasons. It's because the game uses -255 through 255 for UV values and converts them to floats.

**Comment by KayaneRF** [comment]
𝘞𝘩𝘺 𝘤𝘭𝘰𝘴𝘦𝘥? 𝘐 𝘩𝘢𝘷𝘦 𝘢 𝘲𝘶𝘦𝘴𝘵𝘪𝘰𝘯.

𝘘 ~ “𝘐𝘯 𝘭𝘢𝘵𝘦𝘳 𝘳𝘦𝘭𝘦𝘢𝘴𝘦𝘴  (𝘜𝘚/𝘐𝘯𝘵𝘦𝘳𝘯𝘢𝘵𝘪𝘰𝘯𝘢𝘭) 𝘰𝘯 𝘵𝘩𝘦 𝘋𝘳𝘦𝘢𝘮𝘤𝘢𝘴𝘵 𝘵𝘩𝘦 𝘦𝘧𝘧𝘦𝘤𝘵 𝘸𝘢𝘴 𝘵𝘰𝘯𝘦𝘥 𝘥𝘰𝘸𝘯, 𝘣𝘶𝘵 𝘺𝘰𝘶 𝘤𝘰𝘶𝘭𝘥 𝘴𝘵𝘪𝘭𝘭 𝘴𝘦𝘦 𝘵𝘩𝘦 𝘴𝘵𝘳𝘦𝘵𝘤𝘩𝘺 𝘴𝘩𝘰𝘦𝘴 𝘴𝘰𝘮𝘦𝘵𝘪𝘮𝘦𝘴.”

𝘚𝘰𝘶𝘳𝘤𝘦 ~ https://dreamcastify.wordpress.com/2017/11/03/character-model-downgrades/

𝘋𝘳𝘦𝘢𝘮𝘤𝘢𝘴𝘵 (𝘐𝘯𝘵𝘦𝘳𝘯𝘢𝘵𝘪𝘰𝘯𝘢𝘭) 𝘳𝘦𝘴𝘵𝘰𝘳𝘢𝘣𝘭𝘦? 𝘉𝘦𝘴𝘵 𝘳𝘦𝘨𝘶𝘢𝘳𝘥𝘴,
–𝘒𝘢𝘺𝘢𝘯𝘦

**Comment by ItsEasyActually** [comment]
That was restored in [this mod](https://github.com/SonicFreak94/sadx-onion-blur) by SonicFreak94. Also I closed this issue because there's no easy fix for this as it is mostly a precision issue.

**Comment by KayaneRF** [comment]
𝘕𝘰 𝘣𝘭𝘶𝘳. x0 𝘐 𝘲𝘶𝘦𝘴𝘵𝘪𝘰𝘯 𝘧𝘦𝘦𝘵.

𝘘𝘶𝘰𝘵a
![nkjntybu4](https://user-images.githubusercontent.com/34458147/35181426-46f34500-fd8f-11e7-897a-7c08f8715405.png)
𝘑𝘢𝘱𝘢𝘯, 𝘺𝘦𝘴. 𝘜𝘚/𝘐𝘯𝘵𝘦𝘳𝘯𝘢𝘵𝘪𝘰𝘯𝘢𝘭, 𝘯𝘰.

𝘋𝘳𝘦𝘢𝘮𝘤𝘢𝘴𝘵 (𝘜𝘚/𝘐𝘯𝘵𝘦𝘳𝘯𝘢𝘵𝘪𝘰𝘯𝘢𝘭) 𝘵𝘰𝘯𝘦𝘥 𝘥𝘰𝘸𝘯 𝘴𝘵𝘳𝘦𝘵𝘤𝘩 𝘵𝘺𝘱𝘦 𝘤𝘢𝘯 𝘣𝘦 𝘮𝘢𝘥𝘦?
–𝘒𝘢𝘺𝘢𝘯𝘦
