### ISSUE TITLE
Add a configschema.xml for the SADX Mod Manager Configuration Menu

### ISSUE THREAD

**Issue by cheatfreak47** [ItsEasyActually/SA1_Chars#15]
It's as the title suggests- a configschema.xml for the new config menu would allow a GUI to edit the mod settings, which is of course- useful.

**Comment by ItsEasyActually** [comment]
This will be in the next update as soon as I get things fixed to work with it. It's merging Metal Sonic's hover options and the Stretchy Shoe options into single groups for much easier use.

**Comment by cheatfreak47** [comment]
Per my own suggestions, good to know, excited for the update
