### ISSUE TITLE
Higher-res textures

### ISSUE THREAD

**Issue by Sonikko** [ItsEasyActually/SA1_Chars#16]
Hey there!
Speeps found out something interesting. It looks like Shuffle has some higher res versions (2x the original res) of the character textures from SA1. I implemented some of them to see how they would look like, I'll post some comparisons.
![untitled-1](https://user-images.githubusercontent.com/24740235/36213547-490ec8f6-11a7-11e8-9246-d42848881f3e.png)
Changed: Belt (b_beruto, b_beruto3, b_beruto5), hands (b_hand0), fishing rod's reel (b_sao01 not really noticeable, but SA1's texture is 8x8 and Shuffle's is 16x16).
![untitled-2](https://user-images.githubusercontent.com/24740235/36213999-80b22e50-11a8-11e8-8990-e0603c304738.png)
Changed: Eyes (mtx_eye3), hands/gloves hole(s_anakage, s_testhand), tails (mtx_tail), belly (mtx_shitahara, I think it's the belly?)
Those are a couple of examples, I thought maybe you'd be interested in this, a configurable option with higher-res textures would be cool!
Also, Big has some transparency issues on the belt, it happens with the standard textures aswell, haven't seen it mentioned anywhere.

[textures.zip](https://github.com/ItsEasyActually/SA1_Chars/files/1725352/textures.zip)

These are the texture packs if you wanna test them. Sonic, Amy and Knuckles have some edits too. Sonic has higher res eyes, hands and a higher res shoe buckle, Amy and Knuckles have higher res eyes.

Edit: Adding Sonic comparison shots
![untitled-1](https://user-images.githubusercontent.com/24740235/36223376-8e77c682-11c4-11e8-9e71-61cb7245eb11.png)
![untitled-2](https://user-images.githubusercontent.com/24740235/36223377-8e968d56-11c4-11e8-9b7a-b01091a7618d.png)
stx_eye2 is manually edited, took Amy's eye texture and edited the white shine, stx_hara is custom, I used stx_btest1 as a base and drew a skin colored ellipse over it.
The shoe buckle and hand texture are from Shuffle.

EDIT 16/02/2018:
I found out the Autodemo has some higher resolution textures aswell, without the quality loss the ones from Shuffle suffered from. Amy has higher res headband and hammer textures, Big has even better belt textures and fishing rods, Knuckles and Sonic have better muzzle textures, Sonic has a better shoe buckle.
I gave Tikal higher-res hands aswell, since she had some tiny and heavily compressed textures for them.
![image](https://user-images.githubusercontent.com/24740235/36323530-84708df2-1351-11e8-81af-1fc02ff3d220.png)
![image](https://user-images.githubusercontent.com/24740235/36323536-8c3b076a-1351-11e8-92e3-ece85d791d0b.png)
![image](https://user-images.githubusercontent.com/24740235/36328347-11979594-1362-11e8-9260-cc55cae83813.png)

**Comment by ItsEasyActually** [comment]
After a Twitter poll, I will be including a config options for higher resolution textures. None of them will be coming from Sonic Shuffle despite the poll however. None of those textures are actually higher resolution. They're just up-scaled or stretched variations on the existing SA1 textures. The AutoDemo is the only source of actually higher resolution textures.

**Comment by Sonikko** [comment]
Tails' eyes seem to be the only texture from Shuffle to be higher quality or higher resolution compared to the Autodemo. Maybe Big's hands textures were also from Shuffle? I can't recall right now. 
Amy has higher resolution hands textures than every other character in the final game aswell, the texture itself looks the same for the other characters, just half the resolution and with more compression.

**Comment by ItsEasyActually** [comment]
Alright, so these have just been added natively for the foreseeable future as I no longer see a reason to keep both sets of the textures. Closing this for the time being as it's been resolved.
