### ISSUE TITLE
Chaos...?

### ISSUE THREAD

**Issue by ElectroNuke** [ItsEasyActually/SA1_Chars#17]
Hey, I was wondering: are you planning to add Chaos's model, or at least for his first form? I'd love to see that solid puddle from the Dreamcast version. Great progress, though.

**Comment by PiKeyAr** [comment]
Why do you think its model is different from the Dreamcast version?

**Comment by ElectroNuke** [comment]
Ah. So, there isn't any work-around? That's fine, the progress has been mind-blowing.
