### ISSUE TITLE
Saturn Tornado (Again)

### ISSUE THREAD

**Issue by ElectroNuke** [ItsEasyActually/SA1_Chars#19]
Looks like the Saturn Tornado model in Sky Chase isn't working, even when enabled...

**Comment by ItsEasyActually** [comment]
Hm. I changed around its code in the recent update, so I wonder what I broke. I'll look into it.

Thanks for the report!

**Comment by ElectroNuke** [comment]
Yup.

**Comment by PiKeyAr** [comment]
As I said on the IRC, I ran into a similar problem with another mod previously, and what fixed it for me was changing the defaultvalue "true" and "false" fields in the configschema to "True" and "False".

**Comment by ItsEasyActually** [comment]
It's probably that or I messed up with a variable name like I did with the LSDash Shoe config when I updated everything this last time.

**Comment by ElectroNuke** [comment]
No, I just tested it out, and it works okay. I also have something else to bring up, but that's a story for another webpage.
