### ISSUE TITLE
Super Sonic appears as Sonic...?

### ISSUE THREAD

**Issue by ElectroNuke** [ItsEasyActually/SA1_Chars#20]
Apparently, in the cutscene just before the Perfect Chaos boss, Super Sonic is still normal Sonic and only changes in-game. Any clue about that?

**Comment by ItsEasyActually** [comment]
This is not an issue with this mod. I have been trying to find where this issue originally was discussed and resolved, but I'm having no luck finding it. If memory serves, it had something to do with either one of the codes being enabled or another mod being loaded. I wish I could find the original issue, but I don't know what repo it was posted to.

**Comment by ItsEasyActually** [comment]
https://github.com/sonicretro/sadx-super-sonic/issues/18

Found it. Update this mod and it should be fixed.
