### ISSUE TITLE
AutoDemo Textures

### ISSUE THREAD

**Issue by Shadowboxer2005** [ItsEasyActually/SA1_Chars#21]
I've recently ported the Sonic Adventure Autodemo's character textures. (higher quality)
You should add an option to enable the Autodemo's textures.
(Seriously, who made the texture's lower res in the final?)

**Comment by ItsEasyActually** [comment]
This and Issue #16 are the same issue. Both are being resolved by the default inclusion of the higher res textures as I no longer see a need to include the original ones with higher res textures available for use.
