### ISSUE TITLE
Saturn Tornado (Sigh...)

### ISSUE THREAD

**Issue by ElectroNuke** [ItsEasyActually/SA1_Chars#23]
I noticed that the tornado models in Sky Chase have the same EV cutscene models even with "disable Saturn Sky Chase" disabled. Looks like the Saturn models aren't working anymore. Is this a real issue or is it just for me?

**Comment by RinMaru** [comment]
yea Saturn models are broke

**Comment by ItsEasyActually** [comment]
I'm literally so dumb all the time. Why am I even a modder?

In all seriousness, this has been fixed and it's been pushed. Thanks @PiKeyAr
