### ISSUE TITLE
Big belt buckle issue...

### ISSUE THREAD

**Issue by ElectroNuke** [ItsEasyActually/SA1_Chars#25]
I'm not sure if this from the most recent update, but Big's belt buckle is just a beige square now.

![Desktop Screenshot 2019 06 07 - 16 00 51 94](https://user-images.githubusercontent.com/33000916/59130589-df11b200-893d-11e9-86fd-51cc3934a704.png)

**Comment by ItsEasyActually** [comment]
Already fixed, next update should be out shortly. (Within 24 hours hopefully).
