### ISSUE TITLE
Gamma's Missing Idle Animation

### ISSUE THREAD

**Issue by sa-nd** [ItsEasyActually/SA1_Chars#31]
For whatever reason, Gamma no longer use's his idle animation, he still use's his idle dialogue though. Instead of his idle animation, Gamma freezes like this while still saying his line, he doesn't comes out of this frozen trance until you start moving again.

![20190814155259_1](https://user-images.githubusercontent.com/52898048/63062425-c083e600-bead-11e9-94cc-430d136a419d.png)

**Comment by ItsEasyActually** [comment]
I'm going to need more information, like what other mods you're currently loading. Gamma in this mod is only material modifications. I'm not modifying the model nor animations, so this is unlikely to be related to my mod.

**Comment by sa-nd** [comment]
Hm...
Here's all the mods I had loaded when I discovered this.

- SADX;FE

- HD GUI 2

- Sound Overhaul

- Dreamcast Characters Pack

- Dreamcast Conversion

- DLC Circuits

- Lantern Engine

- Onion Blur 

- Fixes, Adds and Beta Restores

- Egg Carrier Garden Ocean fix

- Egg Carrier Ocean Music

- Idle Chatter

- Input Mod

- Metal Sonic Sounds fix

- Pause Hide

- Smooth Camera

- Super Sonic

- Time of Day

**Comment by ItsEasyActually** [comment]
I showed this to @supercoolsonic as I know he had a mod modifying the animations for the characters. He ran a quick test, and it would appear it's caused by his Fixes, Adds, and Beta Restores mod. He's currently working on a patch.

**Comment by sa-nd** [comment]
Whoops wrong mod! 
Thanks for the speedy response anyway!

**Comment by ItsEasyActually** [comment]
Aaaaaaaaand he just updated it to resolve the issues. 

And no prob, currently working on another update to this so I was concerned there might be a bug that needed to be heavily patched lol.

**Comment by supercoolsonic** [comment]
Yes, it's fixed, and will be available in the next release.

**Comment by sa-nd** [comment]
Excellent!
