### ISSUE TITLE
Palette selection for Lantern API

### ISSUE THREAD

**Issue by PiKeyAr** [ItsEasyActually/SA1_Chars#5]
List of palette selection differences for various models

Tails' crashing cutscene (SADX on the right)
![image](https://user-images.githubusercontent.com/23312549/29741851-b2e96f9e-8aaf-11e7-8561-adf343ed06fb.png)

Tails' first custcene
![image](https://user-images.githubusercontent.com/23312549/29773892-63c90a46-8c3a-11e7-9dca-3e8add333686.png)
![image](https://user-images.githubusercontent.com/23312549/29773917-8196cfa4-8c3a-11e7-892d-538b431ea9aa.png)

Tails' upgrade in Station Square main area
![image](https://user-images.githubusercontent.com/23312549/29774663-421def3a-8c3d-11e7-8734-cca9d6074404.png)

Tails' shoes (SA1 on the left)
![image](https://user-images.githubusercontent.com/23312549/29741864-eb98cdb2-8aaf-11e7-825b-deded9e06a7f.png)

Tornado 1 event model
![image](https://user-images.githubusercontent.com/23312549/29741842-7a249864-8aaf-11e7-9ecb-0474dd372044.png)

Tornado 1 gameplay model
![image](https://user-images.githubusercontent.com/23312549/29741841-75dc830c-8aaf-11e7-895c-2d47cbc8416f.png)

Tornado 1 hit model
![image](https://user-images.githubusercontent.com/23312549/29741898-8384d65c-8ab0-11e7-8660-aca11832a9f8.png)

Tornado 1 takeoff in Tails' story
![image](https://user-images.githubusercontent.com/23312549/29775737-4a63bc5c-8c41-11e7-9e14-12101684277c.png)

Tornado 2 event model (almost missed the frame, but all logos should have the "character" palettes)
![image](https://user-images.githubusercontent.com/23312549/29746515-8c0e1948-8b17-11e7-9df8-8a4fa52ce102.png)
![image](https://user-images.githubusercontent.com/23312549/29746521-be35821c-8b17-11e7-863d-111cdc921b85.png)
The propeller should also use character palettes. Also something's up with the emerald inside - possibly wrong palette, alpha issues or lack of ignore light flag. It seems all Tornado models are affected by this.
![image](https://user-images.githubusercontent.com/23312549/29746527-e801dadc-8b17-11e7-9d9a-f3acc46e1279.png)
![image](https://user-images.githubusercontent.com/23312549/29746535-294bd880-8b18-11e7-8dd5-ce7c65b0893a.png)

Tornado 2 gameplay model: Sonic's eyes and nose, shoes
SADX - ![image](https://user-images.githubusercontent.com/23312549/29741857-d1ad7d6c-8aaf-11e7-9bde-24d95f137b5d.png)
SA1 - ![image](https://user-images.githubusercontent.com/23312549/29741859-d76503f6-8aaf-11e7-82bc-a85002d48176.png)

Tornado 2 transformation cutscene
![image](https://user-images.githubusercontent.com/23312549/29741852-ba3c50c2-8aaf-11e7-8c7b-679cf96414af.png)

Tornado 2 transformed event model
![image](https://user-images.githubusercontent.com/23312549/29746562-057f81a8-8b19-11e7-882f-a0458c151a63.png)
Also it looks like material colors on this model aren't fixed yet. Tails looks more orange than his gameplay model. Same with Sonic's shoes.
![image](https://user-images.githubusercontent.com/23312549/29886583-82fae94a-8df5-11e7-9995-c5a136e19146.png)

**Comment by PiKeyAr** [comment]
It looks like the recent update fixed some of this stuff but some other stuff broke:
Tornado 1 model: the logos shouldn't ignore lighting and palette selection is still off, also something's wrong with Sonic's face
![image](https://user-images.githubusercontent.com/23312549/31574465-97983428-b10b-11e7-8d37-8806b1c89708.png)
Tornado 1 hit model
![image](https://user-images.githubusercontent.com/23312549/31574475-bde4076a-b10b-11e7-8775-998eac677a69.png)
Tornado 2 model
![image](https://user-images.githubusercontent.com/23312549/31574476-cf977500-b10b-11e7-8bd5-f94a0e87f4bd.png)

I wanted to fix some of these myself but the materials in the source have arbitrary names rather the ones in DC models, so matching them up with what was there originally would take a lot of time.

**Comment by ItsEasyActually** [comment]
I have no idea how any of that stuff was changed, I didn't touch it in the recent update so that is odd.

**Comment by PiKeyAr** [comment]
It might be specific to the low-poly Tornado models, which I had enabled for the last comparison. But Sonic in Chaos 4 and Super Sonic are fixed.

**Comment by ItsEasyActually** [comment]
This is a task list to keep up with what's been fixed and what hasn't in terms of the Palette Lighting API.

- [ ] Tails Event Model
- [x] Tails Jet Anklet
- [ ] Crashed Tails in Emerald Coast
- [x] Event Tornado 1
- [x] Sky Chase Tornado 1 (Event version)
- [x] Sky Chase Tornado 1 (Saturn version)
- [ ] Tornado 1 Broken
- [ ] Event Tornado 2 (Before)
- [ ] Sky Chase Tornado 2 (Event version)
- [ ] Sky Chase Tornado 2 (Saturn version)
- [ ] Tornado 2 Transformation
- [ ] Event Tornado 2 (After)

This will be updated as I make changes until all changes are complete.

**Comment by PiKeyAr** [comment]
I'll recheck more thorougly in my next test playthrough, but these should be fixed now.
