### ISSUE TITLE
Tornado Textures...

### ISSUE THREAD

**Issue by ElectroNuke** [ItsEasyActually/SA1_Chars#6]
Hi, it looks like both the remodeled tornado and the original Saturn model had their textures messed up somehow after the Metal Sonic update. Sonic's missing the stripe on his shoe, his beige parts are colored as they were on the DX model, and the eyes on the Saturn model are completely missing! If you don't have the time to make a new update, could you at least post a link to an older version? Thanks.

**Comment by ItsEasyActually** [comment]
It wasn't a texture issue actually, it was a material error. For some reason, the materials missed out on getting their colours removed. This made the models look funky. The fix will be in the next update as soon as I get a fix for another bug from the Metal Sonic update fixed as well.

**Comment by ElectroNuke** [comment]
OK, thanks, I'll check the updates periodically. I appreciate the response. Just getting a bonus episode done to finish off a series on the Dreamcast mods. I added links to all the mods in the description, FYI.

**Comment by ItsEasyActually** [comment]
Oh cool, thanks for that!

**Comment by ElectroNuke** [comment]
Looks awesome, man. Glad to see it updated!
